package com.neaterbits.query.sql.dsl.api;

final class TestInstance {
	private final Object instance;
	private Object pk;
	
	TestInstance(Object instance, Object pk) {
		
		if (instance == null) {
			throw new IllegalArgumentException("instance == null");
		}
		
		/* if PK generated by DB, we do not have PK at time of .add() to the builder
		if (pk == null) {
			throw new IllegalArgumentException("pk == null");
		}
		*/

		this.instance = instance;
		this.pk = pk;
	}

	Object getInstance() {
		return instance;
	}

	Object getPK() {
		return pk;
	}

	public Object getPk() {
		return pk;
	}

	void setPk(Object pk) {
		
		if (pk == null) {
			throw new IllegalArgumentException("pk == null");
		}
		
		if (this.pk != null) {
			throw new IllegalStateException("this.pk != null");
		}

		this.pk = pk;
	}

	@Override
	public String toString() {
		return "TestInstance [instance=" + instance + ", pk=" + pk + "]";
	}
	
	
}
