package com.neaterbits.query.sql.dsl.api;

public interface ISharedMapFunctions_Numeric_Undecided<

		MODEL,
		RESULT,
		
		NAMED_RET extends ISharedSelectSourceBuilder<MODEL, RESULT>,
		ALIAS_RET extends ISharedSelectSourceBuilder<MODEL, RESULT>,
		UNDECIDED_RET extends ISharedSelectSourceBuilder<MODEL, RESULT>,
		
		NAMED_SUM_LONG_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_COUNT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_LENGTH_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BYTE_RET 	 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_SHORT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_INT_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_LONG_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_FLOAT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_DOUBLE_RET     extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,

		NO_PARAM_NAMED_SUM_LONG_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_COUNT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_LENGTH_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BYTE_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_SHORT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_INT_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_LONG_RET 		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BIGINTEGER_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_FLOAT_RET 		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_DOUBLE_RET     extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		
		ALIAS_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_LENGTH_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_FLOAT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		
		NO_PARAM_ALIAS_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_LENGTH_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BIGINTEGER_RET	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_FLOAT_RET		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		
		UNDECIDED_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_LENGTH_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_FLOAT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		UNDECIDED_DATE_RET 		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		
		NO_PARAM_UNDECIDED_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_LENGTH_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_FLOAT_RET		 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
		NO_PARAM_UNDECIDED_DATE_RET 		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>
		
	>

		extends
		/*
				ISharedFunctions_Arithmetic_Named<MODEL, RESULT, NAMED_RET, NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET>,
				ISharedFunctions_Aggregate_Named<NAMED_SUM_LONG_RET, NAMED_COUNT_RET, NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET, NAMED_DATE_RET>,

				ISharedFunctions_Arithmetic_Alias<MODEL, RESULT, ALIAS_RET, ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET>,
				ISharedFunctions_Aggregate_Alias<ALIAS_SUM_LONG_RET, ALIAS_COUNT_RET, ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET, ALIAS_DATE_RET>,
				*/

		/*
		ISharedFunctions_Arithmetic_Undecided<MODEL, RESULT,
						NAMED_RET, ALIAS_RET, UNDECIDED_RET,
						NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET,
						ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET,
						UNDECIDED_BYTE_RET, UNDECIDED_SHORT_RET, UNDECIDED_INT_RET, UNDECIDED_LONG_RET, UNDECIDED_BIGINTEGER_RET, UNDECIDED_FLOAT_RET, UNDECIDED_DOUBLE_RET, UNDECIDED_BIGDECIMAL_RET
						>,
				*/
		ISharedFunctions_NumericResult_Undecided<MODEL, RESULT,
				NAMED_RET, ALIAS_RET, UNDECIDED_RET,
				NAMED_LENGTH_RET, ALIAS_LENGTH_RET,
				NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET,
				ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET,
				UNDECIDED_BYTE_RET, UNDECIDED_SHORT_RET, UNDECIDED_INT_RET, UNDECIDED_LONG_RET, UNDECIDED_BIGINTEGER_RET, UNDECIDED_FLOAT_RET, UNDECIDED_DOUBLE_RET, UNDECIDED_BIGDECIMAL_RET
		>,
						
		ISharedFunctions_Aggregate_Named_All<NAMED_SUM_LONG_RET, NAMED_COUNT_RET, NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET, NAMED_DATE_RET>,

		ISharedFunctions_Aggregate_Alias_All<ALIAS_SUM_LONG_RET, ALIAS_COUNT_RET, ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET, ALIAS_DATE_RET>,
		
		
		// For recursive no-params - but only to other numeric functions, not to string ones 
		ISharedFunctions_Arithmetic_NoParam_Base<
			MODEL, RESULT, 
			ISharedMapFunctions_Numeric_Undecided<
					MODEL, 
					RESULT,
					
					NAMED_RET,
					ALIAS_RET,
					UNDECIDED_RET,
							
					NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_BYTE_RET, NO_PARAM_NAMED_SHORT_RET, NO_PARAM_NAMED_INT_RET, NO_PARAM_NAMED_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_FLOAT_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
					NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_BYTE_RET, NO_PARAM_NAMED_SHORT_RET, NO_PARAM_NAMED_INT_RET, NO_PARAM_NAMED_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_FLOAT_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
					NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_BYTE_RET, NO_PARAM_ALIAS_SHORT_RET, NO_PARAM_ALIAS_INT_RET, NO_PARAM_ALIAS_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_FLOAT_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
					NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_BYTE_RET, NO_PARAM_ALIAS_SHORT_RET, NO_PARAM_ALIAS_INT_RET, NO_PARAM_ALIAS_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_FLOAT_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
					NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_BYTE_RET, NO_PARAM_UNDECIDED_SHORT_RET, NO_PARAM_UNDECIDED_INT_RET, NO_PARAM_UNDECIDED_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_FLOAT_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET,
					NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_BYTE_RET, NO_PARAM_UNDECIDED_SHORT_RET, NO_PARAM_UNDECIDED_INT_RET, NO_PARAM_UNDECIDED_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_FLOAT_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET
					>,
					
					
			// Hack - for sqrt(), we always return double-typem, so all input types must be converted to whatever is DOUBLE_TYPE
			// (which may not be double() if some function earlier have swapped DOUBLE_TYPE for something different)
					
			ISharedMapFunctions_Numeric_Undecided<
					MODEL, 
					RESULT,
					
					NAMED_RET,
					ALIAS_RET,
					UNDECIDED_RET,
							
					NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET,
					NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET,
					NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET,
					NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET,
					NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET,
					NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET
					>							
			>,
					
			ISharedFunctions_Aggregate_NoParam_Base<
					MODEL,
					RESULT,
					
					ISharedMapFunctions_Numeric_Undecided<
							MODEL, 
							RESULT,
							
							NAMED_RET,
							ALIAS_RET,
							UNDECIDED_RET,
									
							NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_BYTE_RET, NO_PARAM_NAMED_SHORT_RET, NO_PARAM_NAMED_INT_RET, NO_PARAM_NAMED_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_FLOAT_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
							NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_BYTE_RET, NO_PARAM_NAMED_SHORT_RET, NO_PARAM_NAMED_INT_RET, NO_PARAM_NAMED_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_FLOAT_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
							NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_BYTE_RET, NO_PARAM_ALIAS_SHORT_RET, NO_PARAM_ALIAS_INT_RET, NO_PARAM_ALIAS_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_FLOAT_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
							NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_BYTE_RET, NO_PARAM_ALIAS_SHORT_RET, NO_PARAM_ALIAS_INT_RET, NO_PARAM_ALIAS_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_FLOAT_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
							NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_BYTE_RET, NO_PARAM_UNDECIDED_SHORT_RET, NO_PARAM_UNDECIDED_INT_RET, NO_PARAM_UNDECIDED_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_FLOAT_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET,
							NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_BYTE_RET, NO_PARAM_UNDECIDED_SHORT_RET, NO_PARAM_UNDECIDED_INT_RET, NO_PARAM_UNDECIDED_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_FLOAT_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET>
					,
					
					// Sum, cast all to long exception Double and BigDecimal
					ISharedMapFunctions_Numeric_Undecided<
						MODEL, 
						RESULT,
						
						NAMED_RET,
						ALIAS_RET,
						UNDECIDED_RET,
								
						NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
						NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
						NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
						NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET,
						NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET,
						NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_BIGINTEGER_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_DOUBLE_RET, NO_PARAM_UNDECIDED_BIGDECIMAL_RET, NO_PARAM_UNDECIDED_DATE_RET>
					,
					
					// Count, always return long-type for all values
					ISharedMapFunctions_Numeric_Undecided<
						MODEL, 
						RESULT,
						
						NAMED_RET,
						ALIAS_RET,
						UNDECIDED_RET,
								
						NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET,
						NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_LENGTH_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_COUNT_RET,
						NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET,
						NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_LENGTH_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_COUNT_RET,
						NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET,
						NO_PARAM_UNDECIDED_SUM_LONG_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_LENGTH_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET, NO_PARAM_UNDECIDED_COUNT_RET>
			>
{

}
