package com.neaterbits.query.sql.dsl.api;

public interface ISharedFunctions_NumericResult_Undecided<
	MODEL,
	RESULT,
	
	
	NAMED_RET extends ISharedFunction_After<MODEL, RESULT>,
	ALIAS_RET extends ISharedFunction_After<MODEL, RESULT>,
	UNDECIDED_RET extends ISharedFunction_After<MODEL, RESULT>,

	NAMED_LENGTH_RET  	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	ALIAS_LENGTH_RET  	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	
	NAMED_BYTE_RET  		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_SHORT_RET  		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_INTEGER_RET  		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_LONG_RET 	 		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_BIGINTEGER_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_FLOAT_RET 	 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_DOUBLE_RET   		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	NAMED_BIGDECIMAL_RET  	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
	
	ALIAS_BYTE_RET  		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_SHORT_RET  		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_INTEGER_RET  		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_LONG_RET 	 		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_BIGINTEGER_RET 	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_FLOAT_RET 	 	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_DOUBLE_RET   		extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	ALIAS_BIGDECIMAL_RET  	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
	
	
	UNDECIDED_BYTE_RET  		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_SHORT_RET  		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_INTEGER_RET  		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_LONG_RET 	 		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_BIGINTEGER_RET 	extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_FLOAT_RET 	 	extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_DOUBLE_RET   		extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>,
	UNDECIDED_BIGDECIMAL_RET  	extends ISharedFunction_Next<MODEL, RESULT, UNDECIDED_RET>>
	
	extends ISharedFunctions_Arithmetic_Undecided<
		MODEL,
		RESULT,
		
		NAMED_RET,
		ALIAS_RET,
		UNDECIDED_RET,
	
		NAMED_BYTE_RET,
		NAMED_SHORT_RET,
		NAMED_INTEGER_RET,
		NAMED_LONG_RET,
		NAMED_BIGINTEGER_RET,
		NAMED_FLOAT_RET,
		NAMED_DOUBLE_RET, 
		NAMED_BIGDECIMAL_RET,
		
		ALIAS_BYTE_RET,
		ALIAS_SHORT_RET,
		ALIAS_INTEGER_RET,
		ALIAS_LONG_RET,
		ALIAS_BIGINTEGER_RET,
		ALIAS_FLOAT_RET,
		ALIAS_DOUBLE_RET, 
		ALIAS_BIGDECIMAL_RET,

		UNDECIDED_BYTE_RET,
		UNDECIDED_SHORT_RET,
		UNDECIDED_INTEGER_RET,
		UNDECIDED_LONG_RET,
		UNDECIDED_BIGINTEGER_RET,
		UNDECIDED_FLOAT_RET,
		UNDECIDED_DOUBLE_RET, 
		UNDECIDED_BIGDECIMAL_RET

		>,
		
	ISharedFunctions_String_NumericResult_Undecided<MODEL, RESULT, NAMED_RET, ALIAS_RET, NAMED_LENGTH_RET, ALIAS_LENGTH_RET> {

}
