package com.neaterbits.query.sql.dsl.api;


/**
 * All functions that can be included in an initial map(), before we decide whether
 * is named or alias based
 * 
 * @author nhl
 *
 */

public interface ISharedMapFunctions_Initial<
		MODEL,
		RESULT,

		NAMED_RET extends ISharedSelectSourceBuilder<MODEL, RESULT>,
		ALIAS_RET extends ISharedSelectSourceBuilder<MODEL, RESULT>,

		NAMED_SUM_LONG_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_COUNT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_LENGTH_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BYTE_RET 	 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_SHORT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_INT_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_LONG_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_FLOAT_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_DOUBLE_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_STRING_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_CALENDAR_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_SQLDATE_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_SQLTIME_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NAMED_SQLTIMESTAMP_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,

		NO_PARAM_NAMED_SUM_LONG_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_COUNT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_LENGTH_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BYTE_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_SHORT_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_INT_RET 		 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_LONG_RET 		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BIGINTEGER_RET 	extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_FLOAT_RET 		extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_DOUBLE_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_STRING_RET 	 extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_CALENDAR_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_SQLDATE_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_SQLTIME_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		NO_PARAM_NAMED_SQLTIMESTAMP_RET extends ISharedFunction_Next<MODEL, RESULT, NAMED_RET>,
		
		ALIAS_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_LENGTH_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BIGINTEGER_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_FLOAT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_STRING_RET 	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_CALENDAR_RET 	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_SQLDATE_RET 	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_SQLTIME_RET 	extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		ALIAS_SQLTIMESTAMP_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,

		NO_PARAM_ALIAS_SUM_LONG_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_COUNT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_LENGTH_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BYTE_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_SHORT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_INT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_LONG_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BIGINTEGER_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_FLOAT_RET		 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_DOUBLE_RET	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_BIGDECIMAL_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_STRING_RET 	 extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_DATE_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_CALENDAR_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_SQLDATE_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_SQLTIME_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>,
		NO_PARAM_ALIAS_SQLTIMESTAMP_RET extends ISharedFunction_Next<MODEL, RESULT, ALIAS_RET>
		>

	extends
	
		ISharedNumericFunctions_Initial<
			MODEL,
			RESULT,
			
			NAMED_RET,
			ALIAS_RET,
			
			NAMED_SUM_LONG_RET, NAMED_COUNT_RET, NAMED_BYTE_RET, NAMED_SHORT_RET, NAMED_INT_RET, NAMED_LONG_RET, NAMED_BIGINTEGER_RET, NAMED_FLOAT_RET, NAMED_DOUBLE_RET, NAMED_BIGDECIMAL_RET, NAMED_DATE_RET,
			NO_PARAM_NAMED_SUM_LONG_RET, NO_PARAM_NAMED_COUNT_RET, NO_PARAM_NAMED_BYTE_RET, NO_PARAM_NAMED_SHORT_RET, NO_PARAM_NAMED_INT_RET, NO_PARAM_NAMED_LONG_RET, NO_PARAM_NAMED_BIGINTEGER_RET, NO_PARAM_NAMED_FLOAT_RET, NO_PARAM_NAMED_DOUBLE_RET, NO_PARAM_NAMED_BIGDECIMAL_RET, NO_PARAM_NAMED_DATE_RET,
			
			ALIAS_SUM_LONG_RET, ALIAS_COUNT_RET, ALIAS_BYTE_RET, ALIAS_SHORT_RET, ALIAS_INT_RET, ALIAS_LONG_RET, ALIAS_BIGINTEGER_RET, ALIAS_FLOAT_RET, ALIAS_DOUBLE_RET, ALIAS_BIGDECIMAL_RET, ALIAS_DATE_RET,
			NO_PARAM_ALIAS_SUM_LONG_RET, NO_PARAM_ALIAS_COUNT_RET, NO_PARAM_ALIAS_BYTE_RET, NO_PARAM_ALIAS_SHORT_RET, NO_PARAM_ALIAS_INT_RET, NO_PARAM_ALIAS_LONG_RET, NO_PARAM_ALIAS_BIGINTEGER_RET, NO_PARAM_ALIAS_FLOAT_RET, NO_PARAM_ALIAS_DOUBLE_RET, NO_PARAM_ALIAS_BIGDECIMAL_RET, NO_PARAM_ALIAS_DATE_RET>,
			
		ISharedStringFunctions_Initial<
			MODEL,
			RESULT,

			NAMED_RET,
			ALIAS_RET,
			
			NAMED_LENGTH_RET, NAMED_STRING_RET,
			ALIAS_LENGTH_RET, ALIAS_STRING_RET> {
}
