package com.neaterbits.query.sql.dsl.api;

public interface ISharedLogical_And_Or_Undecided<
			MODEL,
			RESULT,

			NAMED_AND_CLAUSES extends ISharedLogical_And_Named_All<MODEL, RESULT, NAMED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES>,
			NAMED_OR_CLAUSES  extends ISharedLogical_Or_Named_All<MODEL, RESULT, NAMED_OR_CLAUSES,  NAMED_NESTED_AND_CLAUSES>,
			
			NAMED_NESTED_AND_CLAUSES extends ISharedLogical_And_Named_All<MODEL, RESULT, NAMED_NESTED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES>,
			NAMED_NESTED_OR_CLAUSES  extends ISharedLogical_Or_Named_All <MODEL, RESULT, NAMED_NESTED_OR_CLAUSES,  NAMED_NESTED_AND_CLAUSES>,			
			
			ALIAS_AND_CLAUSES extends ISharedLogical_And_Alias_Base<MODEL, RESULT, ALIAS_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES>,
			ALIAS_OR_CLAUSES  extends ISharedLogical_Or_Alias_Base <MODEL, RESULT, ALIAS_OR_CLAUSES,  ALIAS_NESTED_AND_CLAUSES>,
			
			ALIAS_NESTED_AND_CLAUSES extends ISharedLogical_And_Alias_Base<MODEL, RESULT, ALIAS_NESTED_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES>,
			ALIAS_NESTED_OR_CLAUSES  extends ISharedLogical_Or_Alias_Base <MODEL, RESULT, ALIAS_NESTED_OR_CLAUSES,  ALIAS_NESTED_AND_CLAUSES>,			

			UNDECIDED_AND_CLAUSES extends ISharedLogical_And_Undecided_Base<MODEL, RESULT, NAMED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES, ALIAS_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES>,
			UNDECIDED_OR_CLAUSES  extends ISharedLogical_Or_Undecided_Base <MODEL, RESULT, NAMED_OR_CLAUSES, NAMED_NESTED_AND_CLAUSES, ALIAS_OR_CLAUSES,  ALIAS_NESTED_AND_CLAUSES>,
			
			UNDECIDED_NESTED_AND_CLAUSES extends ISharedLogical_And_Undecided_Base<MODEL, RESULT, NAMED_NESTED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES, ALIAS_NESTED_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES>,
			UNDECIDED_NESTED_OR_CLAUSES  extends ISharedLogical_Or_Undecided_Base <MODEL, RESULT, NAMED_NESTED_OR_CLAUSES,  NAMED_NESTED_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES,  ALIAS_NESTED_AND_CLAUSES>			

		> 
		
		extends
		ISharedLogical_And_Undecided_Base<MODEL, RESULT, NAMED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES, ALIAS_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES>,
		ISharedLogical_And_Undecided_Function<MODEL, RESULT, NAMED_AND_CLAUSES, NAMED_NESTED_OR_CLAUSES, ALIAS_AND_CLAUSES, ALIAS_NESTED_OR_CLAUSES, UNDECIDED_AND_CLAUSES, UNDECIDED_NESTED_OR_CLAUSES>,
		ISharedLogical_Or_Undecided_Base<MODEL, RESULT, NAMED_OR_CLAUSES, NAMED_NESTED_AND_CLAUSES, ALIAS_OR_CLAUSES, ALIAS_NESTED_AND_CLAUSES>,
		ISharedLogical_Or_Undecided_Function<MODEL, RESULT, NAMED_OR_CLAUSES, NAMED_NESTED_AND_CLAUSES, ALIAS_OR_CLAUSES, ALIAS_NESTED_AND_CLAUSES, UNDECIDED_OR_CLAUSES, UNDECIDED_NESTED_AND_CLAUSES>,
		
		// TODO function and and()/or()
		
		ISharedLogical_Base<MODEL, RESULT> {
	
}
